### ISSUE TITLE
Unexpected Resultant Image

### ISSUE THREAD

**Issue by IcedDoggie** [SeungjunNah/DeepDeblur-PyTorch#1]
Good day, 

I had tried to run a **test** on the mentioned datasets based on the commands suggested in the repo, but I could not understand the output. 
![image](https://user-images.githubusercontent.com/4167312/84259990-f4f21e00-ab21-11ea-9e5c-da14d6fbd2fa.png)

Is there anything that I am missing or I did something wrong? 

Thanks for the help and time.

**Comment by SeungjunNah** [comment]
Hi @IcedDoggie,

Did you download the trained model?
What was the exact command you used?
A proper example would be like:
```bash
python main.py --precision half --save_dir REDS_L1 --demo true --demo_input_dir /home/seungjun/Research/dataset/REDS/train/train_blur/000 --demo_output_dir temp
```
Here, the REDS_L1 directory contains the trained model in the README.
Maybe the --save_dir was not set to the trained directory. I get a similar result when using a randomly initialized model. I will clarify the demo command.

**Comment by IcedDoggie** [comment]
It works now! Thanks a lot :) 
The error i made is that I didn not specify REDS_L1.
