### ISSUE TITLE
Error when validating 

### ISSUE THREAD

**Issue by wl082013** [SeungjunNah/DeepDeblur-PyTorch#10]
Hi   I am trying the pytorch 1.5 code,
however, after running  10 epoch, when validation starts, it gives an error  as follows,
In `trainer.test(epoch)`  
if`  `img.ndim` < 4:
AttributeError: 'Tensor' object has no attribute 'ndim'

I am not sure about the reason why this happens, could you provide some help?
thanks

**Comment by SeungjunNah** [comment]
Hi @wl082013,
Can you provide the raw error log including the line number etc.?
What was the exact command you used?

**Comment by wl082013** [comment]
Hi, 
I found the error was caused by pytorch vision problem, and I solved it. pytorch 1.5 has a  `ndim` which previous versions did not have.  Thank you for your quick reply.

**Comment by SeungjunNah** [comment]
Glad you solved it.
