### ISSUE TITLE
Wrong outputs after applying the demo mode on the GOPRO_Large dataset

### ISSUE THREAD

**Issue by MezereonXP** [SeungjunNah/DeepDeblur-PyTorch#12]
Hi Seungjun, 

I am trying to run your PyTorch code in the demo code. I have downloaded your trained models(GOPRO_L1 and GOPRO_L1_amp) and unzip into the corresponding directory and run the main.py in the demo mode successfully. However, I found some wrongs while checking the outputs of your model after applying on the test dataset of the GOPRO_Large. The output picture looked like:
![output](https://s1.ax1x.com/2020/08/02/atTlvR.png)

Could you please give me some tips?

Thanks.

**Comment by SeungjunNah** [comment]
Hi @MezereonXP,

You seem to be experiencing the same issue as #1.
What was your command exactly?
You should set ```--save_dir``` explicitly so that the command knows where the trained parameters are saved.

It should be like:
```bash
python main.py --precision half --save_dir GOPRO_L1 --demo true --demo_input_dir /home/seungjun/Research/dataset/GOPRO_Large/test/GOPR0384_11_00/blur_gamma --demo_output_dir temp
```

**Comment by MezereonXP** [comment]
My command likes:
```shell
python ./src/main.py --save_dir GOPRO_L1_amp --demo true --demo_input_dir ./gopro/blur/ --demo_output_dir ./result
```
Here is the structure of my directories:
```
├── experiment
│   ├── GOPRO_L1
│   └── GOPRO_L1_amp
├── gopro
│   └── blur
├── LICENSE
├── README.md
├── src

```

**Comment by SeungjunNah** [comment]
Can you try executing ```python main.py``` inside ```src``` directory?
I haven't tried ```python ./src/main.py```.
Some paths are relative to the executing directory and it may not work if executed outside ```src```.

**Comment by MezereonXP** [comment]
> Can you try executing `python main.py` inside `src` directory?
> I haven't tried `python ./src/main.py`.
> Some paths are relative to the executing directory and it may not work if executed outside `src`.

Yeah，I really appreciate your help！
I got the right output after I executed inside the src！
