### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by Ryan1997** [SeungjunNah/DeepDeblur-PyTorch#13]
hi, i recently began study your paper and run your code, but have stuck into some problems when running for several days.
I copy your project in the PyCharm，
and modify some options in the 'option.py': (change the batchsize=8 and num_workers=0, test_every=1, ),
then run the 'main.py',
and the result of my console is follwed as below:
===> Loading train dataset: GOPRO_Large
===> Loading test dataset: GOPRO_Large
Loss function: 1*L1
Metrics: PSNR,SSIM
===> Initializing trainer
results are saved in ../experiment\2020-08-08_13-24-35\result
[Epoch 1 / lr 1.00e-04]
Train Loss: 28.5: |███████████████████████| 1051/1051 [1:23:37<00:00, 4.77s/it]
Train Loss: 28.5: |███████████████████████| 1051/1051 [1:23:37<00:00, 4.77s/it]
Test Loss: 24.6 PSNR: 23.76 SSIM: 0.7086: | | 1/1111 [00:15<4:51:40, 15.77s/it]Can't pickle local object 'MultiSaver.begin_background..t'
Traceback (most recent call last):
File "", line 1, in 
File "D:\Anaconda3\install_file\lib\multiprocessing\spawn.py", line 105, in spawn_main
exitcode = _main(fd)
File "D:\Anaconda3\install_file\lib\multiprocessing\spawn.py", line 115, in _main
self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
add: version of torch is '1.7.0.dev20200730', platform is the windows10,
very thanks if you give me some advice!!!

**Comment by SeungjunNah** [comment]
Hi @Ryan1997,

1) You seem to be using another dataset which is not GOPRO_Large or have modified other parts of the code, too.
If the batch size is 8, the progress bar should show total of 262 batches.

2) It seems like you are running on Windows.
I never tested on Windows and python behavior on multiprocessing varies by OS.

Can you
* describe the exact command you used, 
* describe which part and how you modified, 
* and test on Ubuntu?

**Comment by Ryan1997** [comment]
very thanks for replying.
1. sorry for my mistakes, i use batchsize=2, and the process bar is 1051 batches.  and the dataset is the GOPRO_LARGE

- exact command: i didn't run the code in the terminal, so i haven't tried to use the command.  I just ran the 'main.py' in the PyCharm. The code worked but somthing wrong occuerd in the multiprocessing.
maybe my command is like this: python main.py --n_GPUs 1 --batch_size 2 --num_workers 0 --do validate False --test every 1 --data_root 'DeepDeblur\DeepDeblur-PyTorch'

- the part i modified: honestly, I haven't modified your code, i just modified some options in the 'option.py'. I just changed the batchsize=2 and num_workers=0, test_every=1 and some other options.

- test on Ubantu: it's a good idea. I have searched this problem on the Internet, where some people said multiprocessing on the Windows may have some problems? I tried to set num_workers=0, but it didn't work.

**Comment by SeungjunNah** [comment]
If the batch_size is 2, then the number looks right to me.

In this code, there are different usages of multiprocessing.
1) distributed training
2) data loading
3) image saving

--num_workers controls the number of workers for 2) data loading.

But your case seems to be related to 3) as the error log refers to MultiSaver. (defined in utils.py)
If you can compromise image saving time, then a possible workaround would be  simply not using MultiSaver.
You can replace [this line](https://github.com/SeungjunNah/DeepDeblur-PyTorch/blob/master/src/train.py#L176) in train.py with the contents [here](https://github.com/SeungjunNah/DeepDeblur-PyTorch/blob/master/src/utils.py#L104).

Or simply you can try Ubuntu.

**Comment by Ryan1997** [comment]
@SeungjunNah  Yes, something wrong occured in the code 'self.imsaver.save_image(result, names)'. 
Very thanks for your advice and now i have reran the project by replacing the code you mentioned.

- what i delete : some codes relative to the multiprocessing (just several sentences like self.imsaver)

- what i modify: as you suggested, i replace the code you mentioned. the sentences i added are as blow:
`              #self.imsaver.save_image(result, names)  # code replaced here
                
               if result is not None:
                    result = result.cpu().numpy()
                    im_RGB = np.zeros((result.shape[2], result.shape[3], 3))
                    for idx, im in enumerate(result):
                        im_RGB[:, :, 0] = im[0, :, :]
                        im_RGB[:, :, 1] = im[1, :, :]
                        im_RGB[:, :, 2] = im[2, :, :]
                        im_min = im_RGB.min()
                        im_max = im_RGB.max()
                        im_RGB = 255 * (im_RGB - im_min) / (im_max - im_min)
                        im_RGB = Image.fromarray(im_RGB, 'RGB')
                      
                        save_name = os.path.join(self.result_dir, names[idx])
                        save_dir = os.path.dirname(save_name)
                        os.makedirs(save_dir, exist_ok=True)
                        imageio.imwrite(save_name, im_RGB)`

- results: when i reran the code, it could work normally. However, the experiments results seemed a little bad. The output photos generated by Generator are more like noise.....
This is an example of the output. I set --test_every 1, so the program would save the output after the first training epoch.
![000071](https://user-images.githubusercontent.com/20721827/89730489-8e31a800-da71-11ea-95f6-0d3a64546c46.png)

Sorry for taking you so much time...  So I don't know whether it's because lack of training epoch?(maybe not) Or it's because the codes i replaced make mistakes?

**Comment by SeungjunNah** [comment]
There are dimension swaps and image range mismatch.

The ```result``` tensor is in NCHW format (4-dimensional).
[L155](https://github.com/SeungjunNah/DeepDeblur-PyTorch/blob/master/src/utils.py#L155) here transforms the result tensor to imageio compatible format.

So in your case, a replacement could be as follows.
```python
for output_img, save_name in zip(result, save_names):
    output_img = output_img.add_(0.5).clamp_(0, 255).permute(1, 2, 0).to('cpu', torch.uint8).numpy()
    save_name = os.path.join(result_dir, save_name)
    save_dir = os.path.dirname(save_name)
    os.makedirs(save_dir, exist_ok=True)
    imageio.imwrite(save_name, output_img)
```

I didn't run the above snippet so you might need to debug.

**Comment by Ryan1997** [comment]
@SeungjunNah  Very nice of you and very thanks！ 
I have tried the method you suggested and this time it worked.  The output pictures could be saved.
Use the codes below can help project normally worked in platform Win10:(shame of my ugly coding:))
` if result.shape[0] != 0:

                    for idx, im in enumerate(result):
                        im = im.add_(0.5).clamp_(0, 255).permute(1, 2, 0).to('cpu', torch.uint8).numpy()
                        save_name = os.path.join(self.result_dir, names[idx])
                        save_dir = os.path.dirname(save_name)
                        os.makedirs(save_dir, exist_ok=True)
                        imageio.imwrite(save_name, im)`

There exists a new problem in the pictures saved: its color seems more warmly than the original blur picture, that is the generated pictures are more yellow in color.  Does it matter?

Whatever, thnak you for your patient and useful reply!

**Comment by Ryan1997** [comment]
Everything goes ok now.  This time i use the whole train data and after training, the outputs are normal. (I cut down many train data for shorting the debug time before ==!)
