### ISSUE TITLE
I can't find test.py!

### ISSUE THREAD

**Issue by Xuhexin** [SeungjunNah/DeepDeblur-PyTorch#14]

**Comment by SeungjunNah** [comment]
Hi @Xuhexin,

There is no test.py.
main.py with proper arguments would do everything.

If your purpose is to test on GOPRO_Large or REDS dataset, you can try:
```bash
# When you need PSNR and SSIM
python main.py --save_dir GOPRO_L1_amp --dataset GOPRO_Large --do_train false --do_test true --test_every 1 --load_epoch 1000 --start_epoch 1000
```
You can take a look at [demo examples](https://github.com/SeungjunNah/DeepDeblur-PyTorch#demo) and look at option.py for advanced usages.

If the arguments are too complex, let me know your purpose and I will try to give you a proper command.
