### ISSUE TITLE
the problem of dataset

### ISSUE THREAD

**Issue by Xuhexin** [SeungjunNah/DeepDeblur-PyTorch#15]
When I'm running main.py An error occurred: valueerror: num_ samples should be a positive integer value, but got num_ samples=0

Thank you for your answer!

**Comment by SeungjunNah** [comment]
Hi @Xuhexin,

You should put a dataset in a proper location before running main.py
The dataset should be placed under ```args.data_root``` which is by default ```~/Research/dataset```
[Usage examples](https://github.com/SeungjunNah/DeepDeblur-PyTorch#usage-examples)

For example, 
```
~/Research/dataset/GOPRO_Large/train/GOPR0372_07_00/blur_gamma/....
~/Research/dataset/REDS/train/train_blur/000/...
```
