### ISSUE TITLE
which one is the best loss func?

### ISSUE THREAD

**Issue by rascaliz** [SeungjunNah/DeepDeblur-PyTorch#2]
hi. I'm a huge fan of yours.

which loss function is the best in your example and what's the difference?

eg.)
python main.py --n_GPUs 1 --batch_size 8 --loss 1*L1+1*ADV
python main.py --n_GPUs 1 --batch_size 8 --loss 1*L1+3*ADV
python main.py --n_GPUs 1 --batch_size 8 --loss 1*L1+0.1*ADV

i used REDS datasets for train.

thanks.

**Comment by SeungjunNah** [comment]
Hi @rascaliz,

Usually, the L1 loss on training data drops to around 10 and it's up to your choice to balance the losses by the target.
I guess 0.1 would be too small and values around 1 ~ 3 would work.
And the default batch size of this code is 16. Memory would explode if you use a single GPU.
A possible workaround is to use the NVIDIA Apex for mixed-precision training as it could reduce memory usage.
So in your case, the possible commands would be:
```bash
# single GPU with batch size 8
python main.py --n_GPUs 1 --batch_size 8 --loss 1*L1+1*ADV --dataset REDS --do_test false --endEpoch 200 --milestones 100 150 180

# single GPU with batch size 16 by using Amp (install Apex as written in README)
python main.py --n_GPUs 1 --batch_size 16 --loss 1*L1+1*ADV --dataset REDS --do_test false --endEpoch 200 --milestones 100 150 180 --amp true

# 2-GPU with batch size 16
python launch.py --n_GPUs 2 main.py --batch_size 16 --loss 1*L1+1*ADV --dataset REDS --do_test false --endEpoch 200 --milestones 100 150 180
```

**Comment by Ryan1997** [comment]
hi,  i recently began study your paper and run your code,  but have stuck into some problems when running for several days.
I copy your project in the PyCharm，
and modify some options in the 'option.py':  (change the batchsize=8 and num_workers=0, test_every=1, ),
then run the 'main.py', 
and the result of my console is follwed as below:
===> Loading train dataset: GOPRO_Large
===> Loading test dataset: GOPRO_Large
Loss function: 1*L1
Metrics: PSNR,SSIM
===> Initializing trainer
results are saved in ../experiment\2020-08-08_13-24-35\result
[Epoch 1 / lr 1.00e-04]
Train Loss: 28.5: |███████████████████████| 1051/1051 [1:23:37<00:00,  4.77s/it]
Train Loss: 28.5: |███████████████████████| 1051/1051 [1:23:37<00:00,  4.77s/it]
Test Loss: 24.6 PSNR: 23.76 SSIM: 0.7086: |  | 1/1111 [00:15<4:51:40, 15.77s/it]Can't pickle local object 'MultiSaver.begin_background.<locals>.t'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Anaconda3\install_file\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\Anaconda3\install_file\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

add: version of torch is '1.7.0.dev20200730',   platform is the widows10, 

very thanks if you give me some advice!!!
