### ISSUE TITLE
Inquiry into the usage of trained result

### ISSUE THREAD

**Issue by yorklyb** [SeungjunNah/DeepDeblur-PyTorch#23]
Hi，

I‘m wondering if I can use the trained result just like YOLO, e.g. :

import python.darknet as dn

dn.set_gpu(0)
net = dn.load_net(str.encode("cfg/tiny-yolo.cfg"),
                  str.encode("weights/tiny-yolo.weights"), 0)
meta = dn.load_meta(str.encode("cfg/coco.data"))
r = dn.detect(net, meta, str.encode("data/dog.jpg"))
print(r)

I'm doing some research on pose estimation and I feel like deblurring will improve the accuracy. I need to implement it on an autonomous vehicle, so it would be great if I can use the trained result directly in my script.

**Comment by SeungjunNah** [comment]
Sure, you can use the trained weights for your purposes.
