### ISSUE TITLE
Can't download the pretrained weights

### ISSUE THREAD

**Issue by YuepengZhang** [SeungjunNah/DeepDeblur-PyTorch#24]
Dear Author, could you please reupload these files?

**Comment by SeungjunNah** [comment]
What does your error message say?

I don't find problems on my side.
Google drive can block downloads if the daily traffic is too busy. Can you try again?

**Comment by YuepengZhang** [comment]
Thanks for your reply! 
I tried again and have downloaded the weights files you provided successfully. Nice job and thank you again. 😊


发送自 Windows 10 版邮件应用

发件人: Seungjun Nah
发送时间: 2020年12月3日 9:58
收件人: SeungjunNah/DeepDeblur-PyTorch
抄送: Yuepeng Zhang; Author
主题: Re: [SeungjunNah/DeepDeblur-PyTorch] Can't download the pretrainedweights (#24)

What does your error message say?
I don't find problems on my side.
Google drive can block downloads if the daily traffic is too busy. Can you try again?
