### ISSUE TITLE
Initialization method

### ISSUE THREAD

**Issue by maradona20200204** [SeungjunNah/DeepDeblur-PyTorch#25]
My god, the code is a masterpiece!

I have one simple question: what is the initialization method of the convolutional weights, e.g., Xavier initialization or He initialization? Or the code just uses the default initialization method of PyTorch? I cannot find any initialization method in the code, therefore, I think that the code uses the default initialization method of PyTorch. Am I right?

I appreciate your help.

**Comment by SeungjunNah** [comment]
Hi @maradona20200204,

I used the PyTorch default initialization which is the He initialization.
The initialization function for conv layers, `reset_parameters`, can be found here: [conv.py](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/conv.py#L111)
The function, `kaiming_uniform_` is defined here: [init.py](https://github.com/pytorch/pytorch/blob/master/torch/nn/init.py#L352)

**Comment by maradona20200204** [comment]
Thanks!
