### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by ldlshizhu** [SeungjunNah/DeepDeblur-PyTorch#27]
Thank you for your answer ~
As a novice, I would like to ask you another question. What are the functions of "blur", "sharp" and "blur_gamma" in training?
I wish you a happy life ~

**Comment by ldlshizhu** [comment]
I would like to ask when to input the blur_gamma  during the test or training?thank you!

**Comment by SeungjunNah** [comment]
You can use whatever for training but to compare with the results, I set the `blur_gamma` as the standard.
