### ISSUE TITLE
Question about demo test

### ISSUE THREAD

**Issue by sky-fly97** [SeungjunNah/DeepDeblur-PyTorch#30]
Hello,When I use demo mode on my own data, the result is strange. 
`!python launch.py --n_GPUs 1 main.py --save_dir results --demo true --demo_input_dir ../test_data --demo_output_dir Refocus`
Ori image is:
![refocus_005](https://user-images.githubusercontent.com/55578436/113985157-70c21180-987e-11eb-9506-4b86f1842d88.png)
The results is:
![image](https://user-images.githubusercontent.com/55578436/113985186-7a4b7980-987e-11eb-9718-65539e69fa8f.png)

**Comment by sky-fly97** [comment]
And I test the `REDS Blur + Low Resolution test_blur_bicubic.zip`, Why is the image strange and the results are different every time. Is the way I use it is not right?
![image](https://user-images.githubusercontent.com/55578436/113986608-0316e500-9880-11eb-9b63-49e9bfe39b72.png)
![image](https://user-images.githubusercontent.com/55578436/113986630-0611d580-9880-11eb-89f2-d29621dea29a.png)
![image](https://user-images.githubusercontent.com/55578436/113987007-791b4c00-9880-11eb-9802-10ccc24890a3.png)

**Comment by SeungjunNah** [comment]
Hi @sky-fly97,

You have 2 options.
1) Set the `--save_dir` argument to the diwnloaded  experiment directory as shown in README.
ex) `--save_dir GOPRO_L1`

2) Set pretrained model path.
ex) `--pretrained ../experiment/GOPRO_L1/models/model-1000.pt`

**Comment by sky-fly97** [comment]
> Hi @sky-fly97,
> 
> You have 2 options.
> 
> 1. Set the `--save_dir` argument to the diwnloaded experiment directory as shown in README. ex) `--save_dir GOPRO_L1`
> 2. Set pretrained model path. ex) `--pretrained ../experiment/GOPRO_L1/models/model-1000.pt`

Thanks, I misunderstood the meaning of “save_dir”！
