### ISSUE TITLE
Dataset Preparation

### ISSUE THREAD

**Issue by Kamalhsn** [SeungjunNah/DeepDeblur-PyTorch#32]
Hi, 
How did you prepare non-uniform motion blur data?
Is the motion blur generated by automotive camera sensors/self-driving car camera sensors similar to your case?

**Comment by SeungjunNah** [comment]
Hi @Kamalhsn,

We used hand-held cameras for both the GOPRO and the REDS datasets.
I'm not sure what kind of similarity you are referring to but the blur generation principle is not correlated with the camera sensor type and the acquisition environment.
Any high-speed camera would suffice to synthesize motion blur.

Best,
Seungjun
