### ISSUE TITLE
I have trouble when I test the pretrained model.

### ISSUE THREAD

**Issue by ghost** [SeungjunNah/DeepDeblur-PyTorch#33]
I follow the ReadMe to download the GOPRO_L1 pretrained model and unzip it to /experiment folder. However, when I test the pretrained model with a GOPRO blurry image, the output image is like:

![000001](https://user-images.githubusercontent.com/55644082/119831087-7effe600-bf2f-11eb-92ae-e3a56c9bec2c.png)

How to deal with it? Many thanks.

**Comment by ghost** [comment]
I have fixed this problem. My GPU is RTX3090 which does not match Pytorch v1.6 with cudatoolkit 10.2. So I use Pytorch v1.8 and get the right output image.
![000001](https://user-images.githubusercontent.com/55644082/119835943-e5870300-bf33-11eb-9179-954847524cc2.png)

**Comment by SeungjunNah** [comment]
Hi @daoyuli 
Glad you solved the issue.
As far as I know, Ampere GPUs will perform the best with cuda >= 11.0
