### ISSUE TITLE
Incorrect Results?

### ISSUE THREAD

**Issue by Abrar3616** [SeungjunNah/DeepDeblur-PyTorch#34]
HI, thankyou for your contribution. I ran the pre-trained models REDS_L1 and GOPRO_L1 on my own images and even the example images you provided but i am getting bad results. Any idea what it could be? I am running this on windows.  Thanks in advance.

Orig Image

![blur3](https://user-images.githubusercontent.com/74458556/125900589-7093f1ae-ab7b-4a54-b43d-7d25d6eb2319.jpg)

Deblurred with REDS

![blur3](https://user-images.githubusercontent.com/74458556/125900649-f31f1845-c188-4eba-b3fe-53c7c10bb1ad.png)

DeBlurred with GOPRO

![blur3](https://user-images.githubusercontent.com/74458556/125900685-8558e5ce-a68b-4de9-8e7d-d428a4248da0.png)

Your orig example Flower

![Flower_sharp1](https://user-images.githubusercontent.com/74458556/125900755-64733f19-9026-451a-9e14-56a42844c2b8.png)

Deblurred with REDS

![Flower_blur1](https://user-images.githubusercontent.com/74458556/125901149-2e5b40ba-f858-4983-9290-04f2c21347c6.png)

Deblurred with GOPRO

![Flower_blur1](https://user-images.githubusercontent.com/74458556/125900806-e1e4eba6-b8df-4f98-801c-dd2fcbbb14af.png)

Your orig example istanbul

![Istanbul_sharp1](https://user-images.githubusercontent.com/74458556/125900855-79ea0d28-2f4e-475b-9eb4-708c371b3c08.png)

Deblurred with REDS

![Istanbul_blur1](https://user-images.githubusercontent.com/74458556/125901194-0f3f9737-d982-4b3c-a49e-a446f9aa7663.png)

Deblurred with GOPRO
![Istanbul_blur1](https://user-images.githubusercontent.com/74458556/125900887-d984a38a-f573-47c3-8a94-b7dc716248b4.png)

**Comment by SeungjunNah** [comment]
Hi @Abrar3616 

Your GTA image has ghost artifacts instead of blur.
Deblurring methods will not work with it.

To make a more realistic blur, you should increase the frame rates before averaging the successive frames.

**Comment by Abrar3616** [comment]
Oh ok thanks. Ill look into it
