### ISSUE TITLE
Blurry image generation

### ISSUE THREAD

**Issue by zhang-pengyu** [SeungjunNah/DeepDeblur-PyTorch#38]
Thanks for the inspiring work! However, I have a concern on how to generate blurry images. It said "We took 240 fps videos with GOPRO camera and then averaged varying number (7 - 13) of successive latent frames to produce blurs of different strengths."

Does it mean blurry image can be obtained by only averaging some images with 240Hz frame rate?

**Comment by SeungjunNah** [comment]
Hi, Pengyu,

Averaging high-speed video frames could approximately simulate a motion-blurred image. Whether 240fps is enough or not depends on the strength of motion. If motion is too fast, then ghost artifacts will occur. You may want to refer to the REDS dataset which handles this issue with frame interpolation.

**Comment by zhang-pengyu** [comment]
Thanks for your reply. I got it.
