### ISSUE TITLE
Getting Error: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.

### ISSUE THREAD

**Issue by RowanG1** [SeungjunNah/DeepDeblur-PyTorch#39]
I am running on Anaconda, via terminal.

Any ideas?

**Comment by SeungjunNah** [comment]
Hi @RowanG1,

It seems like you are running on Windows. Sorry, I don't gurantee the code running on Windows.
I would recommend starting by checking if PyTorch is installed correctly.

**Comment by Auresol** [comment]
I don't know if the problem has been solved yet. I'm gonna write it anyway.

I run into a similar problem while using jupyter notebook. so I check libiomp5md.dll in my anaconda file. The result was,
![Screenshot 2022-06-19 135321](https://user-images.githubusercontent.com/64572955/174469435-ae2ba1ed-2182-4130-88c9-20b1eefe537d.jpg)

After that, I try to move out (delete) each file to see if it works. It seems like when I delete the one its path was C:\Users\phudi\anaconda3\Library\bin. the code works fine.

I'm neither an expert nor experienced. So I don't know if this approach has any side effects. But it does work for me.
