### ISSUE TITLE
Training Dataset

### ISSUE THREAD

**Issue by SkyeLu** [SeungjunNah/DeepDeblur-PyTorch#4]
Hi, thanks for sharing your code! After reading your code, I found that while training the model on GoPro dataset, you use blur images in _blur_gamma_ folder rather than those in _blur_ folder. Am I correct?

**Comment by SeungjunNah** [comment]
That is correct. ```blur_gamma``` data is what is used in the paper.

**Comment by SkyeLu** [comment]
thx!
