### ISSUE TITLE
KeyError on loss

### ISSUE THREAD

**Issue by RowanG1** [SeungjunNah/DeepDeblur-PyTorch#40]
Running: Ubuntu.

Executed command: 
`python main.py --save_dir GOPRO_L1 --demo true --demo_input_dir Input`

Get error:
loss = self.loss_stat[self.mode]['Total'][self.epoch] KeyError: 1001

**Comment by RowanG1** [comment]
Wrong Input directory.

**Comment by anushka17agarwal** [comment]
I'm having the same error. I download a blurred image and saved it in input directory copied its relative path and gave that as an arg

**Comment by anushka17agarwal** [comment]
I think you getting that error because your input directory is inside the repo directory. Try putting it outside the project folder and give its absolute path
