### ISSUE TITLE
Using blurred images only, how to train your code??

### ISSUE THREAD

**Issue by edwardcho** [SeungjunNah/DeepDeblur-PyTorch#42]
Hello sir,
I have interesting image deblurring and i searched your code.
I had tried your sample data(gopro).
I checked your sample data that is paired datasets.(blurred image vs sharp image)
But i have blurred images only.
Can i try to train your code??

Thanks,
Edward Cho.

**Comment by SeungjunNah** [comment]
This repository is for supervised training method introduced in the CVPR 2017 publication,
If you want to train without paired sharp images, you might be interested in self-supervised or unsupervised methods.
ex)
N. T. Madam et al., "Unsupervised Class-Specific Deblurring," ECCV 2018
B. Lu et al., "Unsupervised Domain-Specific Deblurring via Disentangled Representations," CVPR 2019

Best,
Seungjun

**Comment by edwardcho** [comment]
Hello Sir,

Thank you for your response quickly.

According to your comments, I will search another papers.

Thanks.
Edward Cho.

**Comment by edwardcho** [comment]
Hello Sir,

I checked your comment paper.
'B. Lu et al., "Unsupervised Domain-Specific Deblurring via Disentangled Representations," CVPR 2019'
Unfortunately, the input-format of this paper is images_A and images_B, but not paired image-set.
As you know, I want to network that has blurred images only as inputs.

Thanks,
Edward Cho.

**Comment by vaseline555** [comment]
Dear @edwardcho, 
Though this paper is not for deblurring, I recommend you this paper: Unsupervised Image Restoration Using Partially Linear Denoisers (TPAMI 2021) https://ieeexplore.ieee.org/document/9395217
As deblurring or restoration is an ill-posed problem, it is demanding to acheive the task objective in a pure unsupervised manner, I think.
