### ISSUE TITLE
Get unexpected results from demo

### ISSUE THREAD

**Issue by XCR16729438** [SeungjunNah/DeepDeblur-PyTorch#45]
Results form demo(test image is from GOPRO):
![0000011](https://user-images.githubusercontent.com/108379675/177005466-81766410-40ee-4219-a806-1f45acc37eab.png)
![0000014](https://user-images.githubusercontent.com/108379675/177005467-4d456154-7221-4d43-b0c2-c5803c1bb43f.png)

Environment:
Windows 10 with Anaconda3,
python 3.7.13, pytorch 1.7.0, cudnn 8.2.1, cudatoolkit 11.0.221,
(Because RTX3060 in my machine do not surpport cuda<=10,
and pytorch 1.6 do not surpport cuda>=11, I cannot use pytorch 1.6.0)
tqdm 4.64.0, imageio 2.9.0, scikit-image 0.18.3, numpy 1.19.2, matplotlib 3.5.1, pyreadline 2.1

Test Command:
`python main.py --save_dir GOPRO_L1 --demo true --demo_input_dir GOPRO_Large/MyTest --demo_output_dir GOPRO_Large/MyResult`

I modified `utils.py` as [this issue](https://github.com/SeungjunNah/DeepDeblur-PyTorch/issues/18), and changed nothing else.
I want to know why I got this result and what should I do to get correct result.

**Comment by SeungjunNah** [comment]
Hi @XCR16729438,

Did you download the pretrained model weights?
Please refer to #1. Your case seems to be the same one.

**Comment by XCR16729438** [comment]
I see, I really downloaded model files, but I just put them in ./src.
I didn't notice that I should put them in ./experiment.
Now the demo works very well, thanks!
