### ISSUE TITLE
dataset folder

### ISSUE THREAD

**Issue by world2025** [SeungjunNah/DeepDeblur-PyTorch#6]
hello, thanks for your codes, i want to know how to create the dataset folder likes GOPRO dataset ,thx!

**Comment by SeungjunNah** [comment]
Hi @tkone2018,
I didn't precisely understand what you mean.
Do you mean you want to know how to construct the GOPRO dataset?
Or the args.data_root folder here:
```python
group_data.add_argument('--data_root', type=str, default='~/Research/dataset', help='dataset root location')
```
For the dataset construction, you can refer to equation 2 in the paper.
To create the dataset folder, I simply used ```mkdir``` command.
The data structure should look like "dataset/GOPRO_Large/train/GOPRxxxx_xx_xx/blur_gamma/xxxxxx.png"

**Comment by world2025** [comment]
emm, construct GOPRO dataset tree, i download the datast likes this: 
HR HR_blur LR LR_blur, so i do not know how to construct the datasete tree like yours

**Comment by SeungjunNah** [comment]
It seems like you have downloaded the REDS dataset which is different from the GOPRO_Large dataset.

If you look into the [Datasets](https://github.com/SeungjunNah/DeepDeblur-PyTorch#datasets) section, there are two different links for GOPRO and REDS.
Here's the direct link for the [GOPRO_Large](https://drive.google.com/file/d/1H0PIXvJH4c40pk7ou6nAwoxuR4Qh_Sa2/view?usp=sharing) dataset.
It contains the file structure like above.

**Comment by world2025** [comment]
aha,i can not use google now

**Comment by SeungjunNah** [comment]
Ok, you can use this link then.
https://cv.snu.ac.kr/~snah/Deblur/dataset/GOPRO_Large.zip

**Comment by world2025** [comment]
ok, thank you
